name: hello_flutter
description: "Slushi app"
publish_to: "none"

version: 1.0.0+18

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # WebView (pin)
  webview_flutter: 4.5.0

  # Map + gps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0

  # HTTP (pin to avoid Dart >=3.2)
  http: 1.1.0

  # Images + navigate
  cached_network_image: ^3.3.1
  url_launcher: 6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: assets/icon_foreground.png
  adaptive_icon_background: "#AEE8FF"
